import 'dotenv/config'

export const env = {
  MONGODB_URI: process.env.MONGO_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  APP_PORT: process.env.PORT,
  BUILD_MODE: process.env.BUILD_MODE,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  SALT_ROUNDS: process.env.SALT_ROUNDS,
  CLIENT_URL: process.env.CLIENT_URL,
  CLIENT_URL_PROD: process.env.CLIENT_URL_PROD,
  CLIENT_URL_PROD2: process.env.CLIENT_URL_PROD2,
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
  SUPABASE_PROJECT_URL: process.env.SUPABASE_PROJECT_URL,
  SUPABASE_ANON_API_KEY: process.env.SUPABASE_ANON_API_KEY,
  SUPABASE_BUCKET_NAME: process.env.SUPABASE_BUCKET_NAME

}